import { Card } from "./card";
import { CardColor } from "./card-color";
import { CardId } from "./card-id";
import { CardPosition } from "./card-position";

export const cards: { [key: string]: Card } = {
  "Baumsproessling": {
    "speci": CardId.SAMPLING,
    "color": CardColor.NONE,
    "position": CardPosition.BASE,
    glCardName: "treeSaplings",
  },
  "Linde": {
    "speci": CardId.LINDEN,
    "color": CardColor.LINDEN,
    "position": CardPosition.BASE,
    glCardName: "linden",
  },
  "Eiche": {
    "speci": CardId.OAK,
    "color": CardColor.OAK,
    "position": CardPosition.BASE,
    glCardName: "oak",
  },
  "Tanne": {
    "speci": CardId.SILVER_FIR,
    "color": CardColor.SILVER_FIR,
    "position": CardPosition.BASE,
    glCardName: "silverFir",
  },
  "Birke": {
    "speci": CardId.BIRCH,
    "color": CardColor.BIRCH,
    "position": CardPosition.BASE,
    glCardName: "birch",
  },
  "Buche": {
    "speci": CardId.BEECH,
    "color": CardColor.BEECH,
    "position": CardPosition.BASE,
    glCardName: "beech",

  },
  "Ahorn": {
    "speci": CardId.SYCAMORE,
    "color": CardColor.SYCAMORE,
    "position": CardPosition.BASE,
    glCardName: "sycamore",
  },
  "Douglasie": {
    "speci": CardId.DOUGLAS_FIR,
    "color": CardColor.DOUGLAS_FIR,
    "position": CardPosition.BASE,
    glCardName: "douglasFir",
  },
  "Kastanie": {
    "speci": CardId.HORSE_CHESTNUT,
    "color": CardColor.HORSE_CHESTNUT,
    "position": CardPosition.BASE,
    glCardName: "horseChestnut",
  },
  "Feldhase_Left_Yellow": {
    "speci": CardId.EUROPEAN_HARE,
    "color": CardColor.LINDEN,
    "position": CardPosition.LEFT,
    glCardName: "europeanHare",
  },
  "Dachs_Right_Grey": {
    "speci": CardId.EUROPEAN_BADGER,
    "color": CardColor.DOUGLAS_FIR,
    "position": CardPosition.RIGHT,
    glCardName: "europeanBadger",
  },
  "Feldhase_Left_Brown": {
    "speci": CardId.EUROPEAN_HARE,
    "color": CardColor.OAK,
    "position": CardPosition.LEFT,
    glCardName: "europeanHare",
  },
  "Hufeisennase_Right_Yellow": {
    "speci": CardId.GREATER_HORSESHOE_BAT,
    "color": CardColor.LINDEN,
    "position": CardPosition.RIGHT,
    glCardName: "greaterHorseshoeBat",
  },
  "Feldhase_Left_Blue": {
    "speci": CardId.EUROPEAN_HARE,
    "color": CardColor.SILVER_FIR,
    "position": CardPosition.LEFT,
    glCardName: "europeanHare",
  },
  "Fuchs_Right_Brown": {
    "speci": CardId.RED_FOX,
    "color": CardColor.OAK,
    "position": CardPosition.RIGHT,
    glCardName: "redFox",
  },
  "Waschbaer_Left_Grey": {
    "speci": CardId.RACCOON,
    "color": CardColor.DOUGLAS_FIR,
    "position": CardPosition.LEFT,
    glCardName: "raccoon",
  },
  "Feldhase_Right_Red": {
    "speci": CardId.EUROPEAN_HARE,
    "color": CardColor.SYCAMORE,
    "position": CardPosition.RIGHT,
    glCardName: "europeanHare",
  },
  "Wildschwein_Left_Red": {
    "speci": CardId.WILD_BOAR,
    "color": CardColor.SYCAMORE,
    "position": CardPosition.LEFT,
    glCardName: "wildBoar",
  },
  "Feldhase_Right_Blue": {
    "speci": CardId.EUROPEAN_HARE,
    "color": CardColor.SILVER_FIR,
    "position": CardPosition.RIGHT,
    glCardName: "europeanHare",
  },
  "Braunes-Langohr_Left_Red": {
    "speci": CardId.BROWN_LONG_EARED_BAT,
    "color": CardColor.SYCAMORE,
    "position": CardPosition.LEFT,
    glCardName: "brownLongEaredBat",
  },
  "Feldhase_Right_Yellow": {
    "speci": CardId.EUROPEAN_HARE,
    "color": CardColor.LINDEN,
    "position": CardPosition.RIGHT,
    glCardName: "europeanHare",
  },
  "Waschbaer_Left_Blue": {
    "speci": CardId.RACCOON,
    "color": CardColor.SILVER_FIR,
    "position": CardPosition.LEFT,
    glCardName: "raccoon",
  },
  "Reh_Right_Green": {
    "speci": CardId.ROE_DEER,
    "color": CardColor.BEECH,
    "position": CardPosition.RIGHT,
    glCardName: "roeDeerBeech",
  },
  "Mopsfledermaus_Left_Orange": {
    "speci": CardId.BARBASTELLE_BAT,
    "color": CardColor.HORSE_CHESTNUT,
    "position": CardPosition.LEFT,
    glCardName: "barbastelleBat",
  },
  "Wildschwein_Right_Brown": {
    "speci": CardId.WILD_BOAR,
    "color": CardColor.OAK,
    "position": CardPosition.RIGHT,
    glCardName: "wildBoar",
  },
  "Braunbaer_Left_Yellow": {
    "speci": CardId.BROWN_BEAR,
    "color": CardColor.LINDEN,
    "position": CardPosition.LEFT,
    glCardName: "brownBear",
  },
  "Waschbaer_Right_Blue": {
    "speci": CardId.RACCOON,
    "color": CardColor.SILVER_FIR,
    "position": CardPosition.RIGHT,
    glCardName: "raccoon",
  },
  "Steinmarder_Left_Red": {
    "speci": CardId.BEECH_MARTEN,
    "color": CardColor.SYCAMORE,
    "position": CardPosition.LEFT,
    glCardName: "beechMarten",
  },
  "Braunbaer_Right_Orange": {
    "speci": CardId.BROWN_BEAR,
    "color": CardColor.HORSE_CHESTNUT,
    "position": CardPosition.RIGHT,
    glCardName: "brownBear",
  },
  "Rothirsch_Left_Yellow": {
    "speci": CardId.RED_DEER,
    "color": CardColor.LINDEN,
    "position": CardPosition.LEFT,
    glCardName: "redDeer",
  },
  "Braunbaer_Right_Green": {
    "speci": CardId.BROWN_BEAR,
    "color": CardColor.BEECH,
    "position": CardPosition.RIGHT,
    glCardName: "brownBear",
  },
  "Mopsfledermaus_Left_Blue": {
    "speci": CardId.BARBASTELLE_BAT,
    "color": CardColor.SILVER_FIR,
    "position": CardPosition.LEFT,
    glCardName: "barbastelleBat",
  },
  "Steinmarder_Right_Orange": {
    "speci": CardId.BEECH_MARTEN,
    "color": CardColor.HORSE_CHESTNUT,
    "position": CardPosition.RIGHT,
    glCardName: "beechMarten",
  },
  "Luchs_Left_Grey": {
    "speci": CardId.LYNX,
    "color": CardColor.DOUGLAS_FIR,
    "position": CardPosition.LEFT,
    glCardName: "lynx",
  },
  "Feldhase_Right_LightGreen": {
    "speci": CardId.EUROPEAN_HARE,
    "color": CardColor.BIRCH,
    "position": CardPosition.RIGHT,
    glCardName: "europeanHare",
  },
  "Wildschwein_Left_LightGreen": {
    "speci": CardId.WILD_BOAR,
    "color": CardColor.BIRCH,
    "position": CardPosition.LEFT,
    glCardName: "wildBoar",
  },
  "Steinmarder_Right_Brown": {
    "speci": CardId.BEECH_MARTEN,
    "color": CardColor.OAK,
    "position": CardPosition.RIGHT,
    glCardName: "beechMarten",
  },
  "Dachs_Left_Orange": {
    "speci": CardId.EUROPEAN_BADGER,
    "color": CardColor.HORSE_CHESTNUT,
    "position": CardPosition.LEFT,
    glCardName: "europeanBadger",
  },
  "Stechmuecke_Right_Brown": {
    "speci": CardId.GNAT,
    "color": CardColor.OAK,
    "position": CardPosition.RIGHT,
    glCardName: "gnat",
  },
  "Fuchs_Left_Yellow": {
    "speci": CardId.RED_FOX,
    "color": CardColor.LINDEN,
    "position": CardPosition.LEFT,
    glCardName: "redFox",
  },
  "Holzbiene_Right_Grey": {
    "speci": CardId.VIOLET_CARPENTER_BEE,
    "color": CardColor.DOUGLAS_FIR,
    "position": CardPosition.RIGHT,
    glCardName: "violetCarpenterBee",
  },
  "Reh_Right_Orange": {
    "speci": CardId.ROE_DEER,
    "color": CardColor.HORSE_CHESTNUT,
    "position": CardPosition.RIGHT,
    glCardName: "roeDeerHorseChestnut",
  },
  "Damhirsch_Left_Yellow": {
    "speci": CardId.FALLOW_DEER,
    "color": CardColor.LINDEN,
    "position": CardPosition.LEFT,
    glCardName: "fallowDeer",
  },
  "Wildschwein_Right_Grey": {
    "speci": CardId.WILD_BOAR,
    "color": CardColor.DOUGLAS_FIR,
    "position": CardPosition.RIGHT,
    glCardName: "wildBoar",
  },
  "Reh_Right_LightGreen": {
    "speci": CardId.ROE_DEER,
    "color": CardColor.BIRCH,
    "position": CardPosition.RIGHT,
    glCardName: "roeDeerBirch",
  },
  "Rothirsch_Left_Blue": {
    "speci": CardId.RED_DEER,
    "color": CardColor.SILVER_FIR,
    "position": CardPosition.LEFT,
    glCardName: "redDeer",
  },
  "Damhirsch_Right_Red": {
    "speci": CardId.FALLOW_DEER,
    "color": CardColor.SYCAMORE,
    "position": CardPosition.RIGHT,
    glCardName: "fallowDeer",
  },
  "Holzbiene_Left_Grey": {
    "speci": CardId.VIOLET_CARPENTER_BEE,
    "color": CardColor.DOUGLAS_FIR,
    "position": CardPosition.LEFT,
    glCardName: "violetCarpenterBee",
  },
  "Luchs_Right_Green": {
    "speci": CardId.LYNX,
    "color": CardColor.BEECH,
    "position": CardPosition.RIGHT,
    glCardName: "lynx",
  },
  "Siebenschlaefer_Left_Green": {
    "speci": CardId.EUROPEAN_FAT_DORMOUSE,
    "color": CardColor.BEECH,
    "position": CardPosition.LEFT,
    glCardName: "europeanFatDormouse",
  },
  "Mopsfledermaus_Right_Brown": {
    "speci": CardId.BARBASTELLE_BAT,
    "color": CardColor.OAK,
    "position": CardPosition.RIGHT,
    glCardName: "barbastelleBat",
  },
  "Hufeisennase_Left_Green": {
    "speci": CardId.GREATER_HORSESHOE_BAT,
    "color": CardColor.BEECH,
    "position": CardPosition.LEFT,
    glCardName: "greaterHorseshoeBat",
  },
  "Siebenschlaefer_Right_Grey": {
    "speci": CardId.EUROPEAN_FAT_DORMOUSE,
    "color": CardColor.DOUGLAS_FIR,
    "position": CardPosition.RIGHT,
    glCardName: "europeanFatDormouse",
  },
  "Wolf_Right_Blue": {
    "speci": CardId.WOLF,
    "color": CardColor.SILVER_FIR,
    "position": CardPosition.RIGHT,
    glCardName: "wolf",
  },
  "Siebenschlaefer_Left_Blue": {
    "speci": CardId.EUROPEAN_FAT_DORMOUSE,
    "color": CardColor.SILVER_FIR,
    "position": CardPosition.LEFT,
    glCardName: "europeanFatDormouse",
  },
  "Braunes-Langohr_Right_Green": {
    "speci": CardId.BROWN_LONG_EARED_BAT,
    "color": CardColor.BEECH,
    "position": CardPosition.RIGHT,
    glCardName: "brownLongEaredBat",
  },
  "Bechsteinfledermaus_Left_Green": {
    "speci": CardId.BECHSTEIN,
    "color": CardColor.BEECH,
    "position": CardPosition.LEFT,
    glCardName: "bechsteinsBat",
  },
  "Siebenschlaefer_Right_Brown": {
    "speci": CardId.EUROPEAN_FAT_DORMOUSE,
    "color": CardColor.OAK,
    "position": CardPosition.RIGHT,
    glCardName: "europeanFatDormouse",
  },
  "Stechmuecke_Left_LightGreen": {
    "speci": CardId.GNAT,
    "color": CardColor.BIRCH,
    "position": CardPosition.LEFT,
    glCardName: "gnat",
  },
  "Wolf_Left_Grey": {
    "speci": CardId.WOLF,
    "color": CardColor.DOUGLAS_FIR,
    "position": CardPosition.LEFT,
    glCardName: "wolf",
  },
  "Stechmuecke_Right_Orange": {
    "speci": CardId.GNAT,
    "color": CardColor.HORSE_CHESTNUT,
    "position": CardPosition.RIGHT,
    glCardName: "gnat",
  },
  "Reh_Left_Yellow": {
    "speci": CardId.ROE_DEER,
    "color": CardColor.LINDEN,
    "position": CardPosition.LEFT,
    glCardName: "roeDeerLinden",
  },
  "Frischling_Right_Red": {
    "speci": CardId.SQUEAKER,
    "color": CardColor.SYCAMORE,
    "position": CardPosition.RIGHT,
    glCardName: "squeaker",
  },
  "Bechsteinfledermaus_Left_Brown": {
    "speci": CardId.BECHSTEIN,
    "color": CardColor.OAK,
    "position": CardPosition.LEFT,
    glCardName: "bechsteinsBat",
  },
  "Reh_Left_Blue": {
    "speci": CardId.ROE_DEER,
    "color": CardColor.SILVER_FIR,
    "position": CardPosition.LEFT,
    glCardName: "roeDeerSilverFir",
  },
  "Luchs_Right_Yellow": {
    "speci": CardId.LYNX,
    "color": CardColor.LINDEN,
    "position": CardPosition.RIGHT,
    glCardName: "lynx",
  },
  "Steinmarder_Left_Green": {
    "speci": CardId.BEECH_MARTEN,
    "color": CardColor.BEECH,
    "position": CardPosition.LEFT,
    glCardName: "beechMarten",
  },
  "Bechsteinfledermaus_Right_LightGreen": {
    "speci": CardId.BECHSTEIN,
    "color": CardColor.BIRCH,
    "position": CardPosition.RIGHT,
    glCardName: "bechsteinsBat",
  },
  "Feldhase_Left_Green": {
    "speci": CardId.EUROPEAN_HARE,
    "color": CardColor.BEECH,
    "position": CardPosition.LEFT,
    glCardName: "europeanHare",
  },
  "Rothirsch_Right_Orange": {
    "speci": CardId.RED_DEER,
    "color": CardColor.HORSE_CHESTNUT,
    "position": CardPosition.RIGHT,
    glCardName: "redDeer",
  },
  "Wolf_Left_Red": {
    "speci": CardId.WOLF,
    "color": CardColor.SYCAMORE,
    "position": CardPosition.LEFT,
    glCardName: "wolf",
  },
  "Frischling_Left_Orange": {
    "speci": CardId.SQUEAKER,
    "color": CardColor.HORSE_CHESTNUT,
    "position": CardPosition.LEFT,
    glCardName: "squeaker",
  },
  "Rothirsch_Right_Brown": {
    "speci": CardId.RED_DEER,
    "color": CardColor.OAK,
    "position": CardPosition.RIGHT,
    glCardName: "redDeer",
  },
  "Fuchs_Left_Green": {
    "speci": CardId.RED_FOX,
    "color": CardColor.BEECH,
    "position": CardPosition.LEFT,
    glCardName: "redFox",
  },
  "Frischling_Right_Brown": {
    "speci": CardId.SQUEAKER,
    "color": CardColor.OAK,
    "position": CardPosition.RIGHT,
    glCardName: "squeaker",
  },
  "Waschbaer_Right_LightGreen": {
    "speci": CardId.RACCOON,
    "color": CardColor.BIRCH,
    "position": CardPosition.RIGHT,
    glCardName: "raccoon",
  },
  "Frischling_Left_Brown": {
    "speci": CardId.SQUEAKER,
    "color": CardColor.OAK,
    "position": CardPosition.LEFT,
    glCardName: "squeaker",
  },
  "Luchs_Right_Blue": {
    "speci": CardId.LYNX,
    "color": CardColor.SILVER_FIR,
    "position": CardPosition.RIGHT,
    glCardName: "lynx",
  },
  "Feldhase_Left_LightGreen": {
    "speci": CardId.EUROPEAN_HARE,
    "color": CardColor.BIRCH,
    "position": CardPosition.LEFT,
    glCardName: "europeanHare",
  },
  "Luchs_Left_Orange": {
    "speci": CardId.LYNX,
    "color": CardColor.HORSE_CHESTNUT,
    "position": CardPosition.LEFT,
    glCardName: "lynx",
  },
  "Fuchs_Right_Grey": {
    "speci": CardId.RED_FOX,
    "color": CardColor.DOUGLAS_FIR,
    "position": CardPosition.RIGHT,
    glCardName: "redFox",
  },
  "Holzbiene_Left_Blue": {
    "speci": CardId.VIOLET_CARPENTER_BEE,
    "color": CardColor.SILVER_FIR,
    "position": CardPosition.LEFT,
    glCardName: "violetCarpenterBee",
  },
  "Damhirsch_Right_LightGreen": {
    "speci": CardId.FALLOW_DEER,
    "color": CardColor.BIRCH,
    "position": CardPosition.RIGHT,
    glCardName: "fallowDeer",
  },
  "Habicht_Grey": {
    "speci": CardId.GOSHAWK,
    "color": CardColor.DOUGLAS_FIR,
    "position": CardPosition.TOP,
    glCardName: "goshawk",
  },
  "Moos_Yellow": {
    "speci": CardId.MOSS,
    "color": CardColor.LINDEN,
    "position": CardPosition.BOTTOM,
    glCardName: "moss",
  },
  "Buntspecht_Yellow": {
    "speci": CardId.GREAT_SPOTTED_WOODPECKER,
    "color": CardColor.LINDEN,
    "position": CardPosition.TOP,
    glCardName: "greatSpottedWoodpecker",
  },
  "Waldameise_LightGreen": {
    "speci": CardId.WOOD_ANT,
    "color": CardColor.BIRCH,
    "position": CardPosition.BOTTOM,
    glCardName: "woodAnt",
  },
  "Buchfink_LightGreen": {
    "speci": CardId.CHAFFINCH,
    "color": CardColor.BIRCH,
    "position": CardPosition.TOP,
    glCardName: "chaffinch",
  },
  "Waldameise_Green": {
    "speci": CardId.WOOD_ANT,
    "color": CardColor.BEECH,
    "position": CardPosition.BOTTOM,
    glCardName: "woodAnt",
  },
  "Waldkauz_Green": {
    "speci": CardId.TAWNY_OWL,
    "color": CardColor.BEECH,
    "position": CardPosition.TOP,
    glCardName: "tawnyOwl",
  },
  "Hirschkaefer_Red": {
    "speci": CardId.STAG_BEETLE,
    "color": CardColor.SYCAMORE,
    "position": CardPosition.BOTTOM,
    glCardName: "stagBeetle",
  },
  "Kaisermantel_Brown": {
    "speci": CardId.SILVER_WASHED_FRITILLARY,
    "color": CardColor.OAK,
    "position": CardPosition.TOP,
    glCardName: "silverWashedFritillary",
  },
  "Feuersalamander_Orange": {
    "speci": CardId.FIRE_SALAMANDER,
    "color": CardColor.HORSE_CHESTNUT,
    "position": CardPosition.BOTTOM,
    glCardName: "fireSalamander",
  },
  "Schillerfalter_Orange": {
    "speci": CardId.PURPLE_EMPEROR,
    "color": CardColor.HORSE_CHESTNUT,
    "position": CardPosition.TOP,
    glCardName: "purpleEmperor",
  },
  "Sumpfschildkroete_Red": {
    "speci": CardId.POND_TURTLE,
    "color": CardColor.SYCAMORE,
    "position": CardPosition.BOTTOM,
    glCardName: "pondTurtle",
  },
  "Trauermantel_Red": {
    "speci": CardId.CAMBERWELL_BEAUTY,
    "color": CardColor.SYCAMORE,
    "position": CardPosition.TOP,
    glCardName: "camberwellBeauty",
  },
  "Sumpfschildkroete_LightGreen": {
    "speci": CardId.POND_TURTLE,
    "color": CardColor.BIRCH,
    "position": CardPosition.BOTTOM,
    glCardName: "pondTurtle",
  },
  "Groser-Fuchs_Blue": {
    "speci": CardId.LARGE_TORTOISESHELL,
    "color": CardColor.SILVER_FIR,
    "position": CardPosition.TOP,
    glCardName: "largeTortoiseshell",
  },
  "Feuersalamander_Grey": {
    "speci": CardId.FIRE_SALAMANDER,
    "color": CardColor.DOUGLAS_FIR,
    "position": CardPosition.BOTTOM,
    glCardName: "fireSalamander",
  },
  "Gimpel_Grey": {
    "speci": CardId.BULLFINCH,
    "color": CardColor.DOUGLAS_FIR,
    "position": CardPosition.TOP,
    glCardName: "bullfinch",
  },
  "Laubfrosch_Yellow": {
    "speci": CardId.TREE_FROG,
    "color": CardColor.LINDEN,
    "position": CardPosition.BOTTOM,
    glCardName: "treeFrog",
  },
  "Buchfink_Red": {
    "speci": CardId.CHAFFINCH,
    "color": CardColor.SYCAMORE,
    "position": CardPosition.TOP,
    glCardName: "chaffinch",
  },
  "Hirschkaefer_LightGreen": {
    "speci": CardId.STAG_BEETLE,
    "color": CardColor.BIRCH,
    "position": CardPosition.BOTTOM,
    glCardName: "stagBeetle",
  },
  "Habicht_Blue": {
    "speci": CardId.GOSHAWK,
    "color": CardColor.SILVER_FIR,
    "position": CardPosition.TOP,
    glCardName: "goshawk",
  },
  "Erdkroete_Brown": {
    "speci": CardId.COMMON_TOAD,
    "color": CardColor.OAK,
    "position": CardPosition.BOTTOM,
    glCardName: "commonToad",
  },
  "Eichelhaeher_LightGreen": {
    "speci": CardId.EURASIAN_JAY,
    "color": CardColor.BIRCH,
    "position": CardPosition.TOP,
    glCardName: "eurasianJay",
  },
  "Baumfarn_Orange": {
    "speci": CardId.TREE_FERNS,
    "color": CardColor.HORSE_CHESTNUT,
    "position": CardPosition.BOTTOM,
    glCardName: "treeFerns",
  },
  "Walderdbeeren_Red": {
    "speci": CardId.WILD_STRAWBERRIES,
    "color": CardColor.SYCAMORE,
    "position": CardPosition.BOTTOM,
    glCardName: "wildStrawberries",
  },
  "Brombeeren_Blue": {
    "speci": CardId.BLACKBERRIES,
    "color": CardColor.SILVER_FIR,
    "position": CardPosition.BOTTOM,
    glCardName: "blackberries",
  },
  "Moos_Grey": {
    "speci": CardId.MOSS,
    "color": CardColor.DOUGLAS_FIR,
    "position": CardPosition.BOTTOM,
    glCardName: "moss",
  },
  "Gluehwuermchen_Yellow": {
    "speci": CardId.FIREFLIES,
    "color": CardColor.LINDEN,
    "position": CardPosition.BOTTOM,
    glCardName: "fireflies",
  },
  "Brombeeren_LightGreen": {
    "speci": CardId.BLACKBERRIES,
    "color": CardColor.BIRCH,
    "position": CardPosition.BOTTOM,
    glCardName: "blackberries",
  },
  "Igel_Green": {
    "speci": CardId.HEDGEHOG,
    "color": CardColor.BEECH,
    "position": CardPosition.BOTTOM,
    glCardName: "hedgehog",
  },
  "Tagpfauenauge_Blue": {
    "speci": CardId.PEACOCK_BUTTERFLY,
    "color": CardColor.SILVER_FIR,
    "position": CardPosition.TOP,
    glCardName: "peacockButterfly",
  },
  "Igel_Brown": {
    "speci": CardId.HEDGEHOG,
    "color": CardColor.OAK,
    "position": CardPosition.BOTTOM,
    glCardName: "hedgehog",
  },
  "Eichhoernchen_Grey": {
    "speci": CardId.RED_SQUIRREL,
    "color": CardColor.DOUGLAS_FIR,
    "position": CardPosition.TOP,
    glCardName: "redSquirrel",
  },
  "Erdkroete_Orange": {
    "speci": CardId.COMMON_TOAD,
    "color": CardColor.HORSE_CHESTNUT,
    "position": CardPosition.BOTTOM,
    glCardName: "commonToad",
  },
  "Eichhoernchen_Orange": {
    "speci": CardId.RED_SQUIRREL,
    "color": CardColor.HORSE_CHESTNUT,
    "position": CardPosition.TOP,
    glCardName: "redSquirrel",
  },
  "Gluehwuermchen_Red": {
    "speci": CardId.FIREFLIES,
    "color": CardColor.SYCAMORE,
    "position": CardPosition.BOTTOM,
    glCardName: "fireflies",
  },
  "Buchfink_Green": {
    "speci": CardId.CHAFFINCH,
    "color": CardColor.BEECH,
    "position": CardPosition.TOP,
    glCardName: "chaffinch",
  },
  "Erdkroete_Blue": {
    "speci": CardId.COMMON_TOAD,
    "color": CardColor.SILVER_FIR,
    "position": CardPosition.BOTTOM,
    glCardName: "commonToad",
  },
  "Gluehwuermchen_Grey": {
    "speci": CardId.FIREFLIES,
    "color": CardColor.DOUGLAS_FIR,
    "position": CardPosition.BOTTOM,
    glCardName: "fireflies",
  },
  "Kaisermantel_Green": {
    "speci": CardId.SILVER_WASHED_FRITILLARY,
    "color": CardColor.BEECH,
    "position": CardPosition.TOP,
    glCardName: "silverWashedFritillary",
  },
  "Tagpfauenauge_Brown": {
    "speci": CardId.PEACOCK_BUTTERFLY,
    "color": CardColor.OAK,
    "position": CardPosition.TOP,
    glCardName: "peacockButterfly",
  },
  "Pfifferling_Blue": {
    "speci": CardId.CHANTERELLE,
    "color": CardColor.SILVER_FIR,
    "position": CardPosition.BOTTOM,
    glCardName: "chanterelle",
  },
  "Tagpfauenauge_Orange": {
    "speci": CardId.PEACOCK_BUTTERFLY,
    "color": CardColor.HORSE_CHESTNUT,
    "position": CardPosition.TOP,
    glCardName: "peacockButterfly",
  },
  "Gluehwuermchen_Green": {
    "speci": CardId.FIREFLIES,
    "color": CardColor.BEECH,
    "position": CardPosition.BOTTOM,
    glCardName: "fireflies",
  },
  "Groser-Fuchs_Red": {
    "speci": CardId.LARGE_TORTOISESHELL,
    "color": CardColor.SYCAMORE,
    "position": CardPosition.TOP,
    glCardName: "largeTortoiseshell",
  },
  "Maulwurf_Brown": {
    "speci": CardId.MOLE,
    "color": CardColor.OAK,
    "position": CardPosition.BOTTOM,
    glCardName: "mole",
  },
  "Igel_Orange": {
    "speci": CardId.HEDGEHOG,
    "color": CardColor.HORSE_CHESTNUT,
    "position": CardPosition.BOTTOM,
    glCardName: "hedgehog",
  },
  "Buntspecht_Grey": {
    "speci": CardId.GREAT_SPOTTED_WOODPECKER,
    "color": CardColor.DOUGLAS_FIR,
    "position": CardPosition.TOP,
    glCardName: "greatSpottedWoodpecker",
  },
  "Eichelhaeher_Red": {
    "speci": CardId.EURASIAN_JAY,
    "color": CardColor.SYCAMORE,
    "position": CardPosition.TOP,
    glCardName: "eurasianJay",
  },
  "Fliegenpilz_Blue": {
    "speci": CardId.FLY_AGARIC,
    "color": CardColor.SILVER_FIR,
    "position": CardPosition.BOTTOM,
    glCardName: "flyagaric",
  },
  "Waldkauz_LightGreen": {
    "speci": CardId.TAWNY_OWL,
    "color": CardColor.BIRCH,
    "position": CardPosition.TOP,
    glCardName: "tawnyOwl",
  },
  "Steinpilz_Grey": {
    "speci": CardId.PENNY_BUN,
    "color": CardColor.DOUGLAS_FIR,
    "position": CardPosition.BOTTOM,
    glCardName: "pennyBun",
  },
  "Eichhoernchen_Green": {
    "speci": CardId.RED_SQUIRREL,
    "color": CardColor.BEECH,
    "position": CardPosition.TOP,
    glCardName: "redSquirrel",
  },
  "Feuersalamander_Yellow": {
    "speci": CardId.FIRE_SALAMANDER,
    "color": CardColor.LINDEN,
    "position": CardPosition.BOTTOM,
    glCardName: "fireSalamander",
  },
  "Schillerfalter_LightGreen": {
    "speci": CardId.PURPLE_EMPEROR,
    "color": CardColor.BIRCH,
    "position": CardPosition.TOP,
    glCardName: "purpleEmperor",
  },
  "Laubfrosch_Brown": {
    "speci": CardId.TREE_FROG,
    "color": CardColor.OAK,
    "position": CardPosition.BOTTOM,
    glCardName: "treeFrog",
  },
  "Tagpfauenauge_Yellow": {
    "speci": CardId.PEACOCK_BUTTERFLY,
    "color": CardColor.LINDEN,
    "position": CardPosition.TOP,
    glCardName: "peacockButterfly",
  },
  "Erdkroete_Green": {
    "speci": CardId.COMMON_TOAD,
    "color": CardColor.BEECH,
    "position": CardPosition.BOTTOM,
    glCardName: "commonToad",
  },
  "Trauermantel_LightGreen": {
    "speci": CardId.CAMBERWELL_BEAUTY,
    "color": CardColor.BIRCH,
    "position": CardPosition.TOP,
    glCardName: "camberwellBeauty",
  },
  "Parasol_Orange": {
    "speci": CardId.PARASOL_MUSHROOM,
    "color": CardColor.HORSE_CHESTNUT,
    "position": CardPosition.BOTTOM,
    glCardName: "parasolMushroom",
  },
  "Habicht_Brown": {
    "speci": CardId.GOSHAWK,
    "color": CardColor.OAK,
    "position": CardPosition.TOP,
    glCardName: "goshawk",
  },
  "Erdkroete_Red": {
    "speci": CardId.COMMON_TOAD,
    "color": CardColor.SYCAMORE,
    "position": CardPosition.BOTTOM,
    glCardName: "commonToad",
  },
  "Eichelhaeher_Orange": {
    "speci": CardId.EURASIAN_JAY,
    "color": CardColor.HORSE_CHESTNUT,
    "position": CardPosition.TOP,
    glCardName: "eurasianJay",
  },
  "Baumfarn_Blue": {
    "speci": CardId.TREE_FERNS,
    "color": CardColor.SILVER_FIR,
    "position": CardPosition.BOTTOM,
    glCardName: "treeFerns",
  },
  "Waldkauz_Red": {
    "speci": CardId.TAWNY_OWL,
    "color": CardColor.SYCAMORE,
    "position": CardPosition.TOP,
    glCardName: "tawnyOwl",
  },
  "Erdkroete_Grey": {
    "speci": CardId.COMMON_TOAD,
    "color": CardColor.DOUGLAS_FIR,
    "position": CardPosition.BOTTOM,
    glCardName: "commonToad",
  },
  "Gimpel_Blue": {
    "speci": CardId.BULLFINCH,
    "color": CardColor.SILVER_FIR,
    "position": CardPosition.TOP,
    glCardName: "bullfinch",
  },
  "Baumfarn_Yellow": {
    "speci": CardId.TREE_FERNS,
    "color": CardColor.LINDEN,
    "position": CardPosition.BOTTOM,
    glCardName: "treeFerns",
  },
  "Eichhoernchen_Brown": {
    "speci": CardId.RED_SQUIRREL,
    "color": CardColor.OAK,
    "position": CardPosition.TOP,
    glCardName: "redSquirrel",
  },
  "Walderdbeeren_LightGreen": {
    "speci": CardId.WILD_STRAWBERRIES,
    "color": CardColor.BIRCH,
    "position": CardPosition.BOTTOM,
    glCardName: "wildStrawberries",
  },
  "Brombeeren_Green": {
    "speci": CardId.BLACKBERRIES,
    "color": CardColor.BEECH,
    "position": CardPosition.BOTTOM,
    glCardName: "blackberries",
  },
  "Schillerfalter_Yellow": {
    "speci": CardId.PURPLE_EMPEROR,
    "color": CardColor.LINDEN,
    "position": CardPosition.TOP,
    glCardName: "purpleEmperor",
  },
  "Fliegenpilz_Brown": {
    "speci": CardId.FLY_AGARIC,
    "color": CardColor.OAK,
    "position": CardPosition.BOTTOM,
    glCardName: "flyagaric",
  },
  "Trauermantel_Orange": {
    "speci": CardId.CAMBERWELL_BEAUTY,
    "color": CardColor.HORSE_CHESTNUT,
    "position": CardPosition.TOP,
    glCardName: "camberwellBeauty",
  },
  "Pfifferling_LightGreen": {
    "speci": CardId.CHANTERELLE,
    "color": CardColor.BIRCH,
    "position": CardPosition.BOTTOM,
    glCardName: "chanterelle",
  },
  "Groser-Fuchs_Green": {
    "speci": CardId.LARGE_TORTOISESHELL,
    "color": CardColor.BEECH,
    "position": CardPosition.TOP,
    glCardName: "largeTortoiseshell",
  },
  "Maulwurf_Red": {
    "speci": CardId.MOLE,
    "color": CardColor.SYCAMORE,
    "position": CardPosition.BOTTOM,
    glCardName: "mole",
  },
  "Parasol_Blue": {
    "speci": CardId.PARASOL_MUSHROOM,
    "color": CardColor.SILVER_FIR,
    "position": CardPosition.BOTTOM,
    glCardName: "parasolMushroom",
  },
  "Europaeische-Laerche": {
    "speci": CardId.LARIX,
    "color": CardColor.LARIX,
    "position": CardPosition.BASE,
    glCardName: "europeanLarch",
  },
  "Zirbelkiefer": {
    "speci": CardId.PINUS,
    "color": CardColor.PINUS,
    "position": CardPosition.BASE,
    glCardName: "stonePine",
  },
  "Alpenmurmeltier_Left_Green": {
    "speci": CardId.MARMOTA_MARMOTA,
    "color": CardColor.BEECH,
    "position": CardPosition.LEFT,
    glCardName: "alpineMarmot",
  },
  "Gaemse_Right_Pink": {
    "speci": CardId.RUPICAPRA_RUPICAPRA,
    "color": CardColor.PINUS,
    "position": CardPosition.RIGHT,
    glCardName: "chamoisStonePine",
  },
  "Alpenmurmeltier_Left_Lila": {
    "speci": CardId.MARMOTA_MARMOTA,
    "color": CardColor.LARIX,
    "position": CardPosition.LEFT,
    glCardName: "alpineMarmot",
  },
  "Auerhuhn_Right_Grey": {
    "speci": CardId.TETRAO_UROGALLUS,
    "color": CardColor.DOUGLAS_FIR,
    "position": CardPosition.RIGHT,
    glCardName: "capercaillie",
  },
  "Schneehase_Left_Blue": {
    "speci": CardId.LEPUS_TIMIDUS,
    "color": CardColor.SILVER_FIR,
    "position": CardPosition.LEFT,
    glCardName: "mountainHare",
  },
  "Alpenmurmeltier_Right_Pink": {
    "speci": CardId.MARMOTA_MARMOTA,
    "color": CardColor.PINUS,
    "position": CardPosition.RIGHT,
    glCardName: "alpineMarmot",
  },
  "Steinbock_Left_Lila": {
    "speci": CardId.CAPRA_IBEX,
    "color": CardColor.LARIX,
    "position": CardPosition.LEFT,
    glCardName: "steinbock",
  },
  "Alpenmurmeltier_Right_LightGreen": {
    "speci": CardId.MARMOTA_MARMOTA,
    "color": CardColor.BIRCH,
    "position": CardPosition.RIGHT,
    glCardName: "alpineMarmot",
  },
  "Gaemse_Left_Lila": {
    "speci": CardId.RUPICAPRA_RUPICAPRA,
    "color": CardColor.LARIX,
    "position": CardPosition.LEFT,
    glCardName: "chamoisEuropeanLarch",
  },
  "Auerhuhn_Right_Green": {
    "speci": CardId.TETRAO_UROGALLUS,
    "color": CardColor.BEECH,
    "position": CardPosition.RIGHT,
    glCardName: "capercaillie",
  },
  "Schneehase_Left_Lila": {
    "speci": CardId.LEPUS_TIMIDUS,
    "color": CardColor.LARIX,
    "position": CardPosition.LEFT,
    glCardName: "mountainHare",
  },
  "Gaemse_Right_Grey": {
    "speci": CardId.RUPICAPRA_RUPICAPRA,
    "color": CardColor.DOUGLAS_FIR,
    "position": CardPosition.RIGHT,
    glCardName: "chamoisDouglasFir",
  },
  "Alpenfledermaus_Left_Blue": {
    "speci": CardId.HYPSUGO_SAVII,
    "color": CardColor.SILVER_FIR,
    "position": CardPosition.LEFT,
    glCardName: "savisPipistrelle",
  },
  "Steinbock_Right_Pink": {
    "speci": CardId.CAPRA_IBEX,
    "color": CardColor.PINUS,
    "position": CardPosition.RIGHT,
    glCardName: "steinbock",
  },
  "Auerhuhn_Left_Lila": {
    "speci": CardId.TETRAO_UROGALLUS,
    "color": CardColor.LARIX,
    "position": CardPosition.LEFT,
    glCardName: "capercaillie",
  },
  "Alpenfledermaus_Right_Pink": {
    "speci": CardId.HYPSUGO_SAVII,
    "color": CardColor.PINUS,
    "position": CardPosition.RIGHT,
    glCardName: "savisPipistrelle",
  },
  "Auerhuhn_Left_Pink": {
    "speci": CardId.TETRAO_UROGALLUS,
    "color": CardColor.PINUS,
    "position": CardPosition.LEFT,
    glCardName: "capercaillie",
  },
  "Steinbock_Right_Grey": {
    "speci": CardId.CAPRA_IBEX,
    "color": CardColor.DOUGLAS_FIR,
    "position": CardPosition.RIGHT,
    glCardName: "steinbock",
  },
  "Alpen-Apollofalter_Pink": {
    "speci": CardId.PARNASSIUS_PHOEBUS,
    "color": CardColor.PINUS,
    "position": CardPosition.TOP,
    glCardName: "phoebusApollo",
  },
  "Herbsttrompete_Lila": {
    "speci": CardId.CRATERELLUS_CORNUCOPIODES,
    "color": CardColor.LARIX,
    "position": CardPosition.BOTTOM,
    glCardName: "blackTrumpet",
  },
  "Alpen-Apollofalter_Grey": {
    "speci": CardId.PARNASSIUS_PHOEBUS,
    "color": CardColor.DOUGLAS_FIR,
    "position": CardPosition.TOP,
    glCardName: "phoebusApollo",
  },
  "Edelweis_Pink": {
    "speci": CardId.LEONTOPODIUM_NIVALE,
    "color": CardColor.PINUS,
    "position": CardPosition.BOTTOM,
    glCardName: "edelweiss",
  },
  "Alpen-Apollofalter_Lila": {
    "speci": CardId.PARNASSIUS_PHOEBUS,
    "color": CardColor.LARIX,
    "position": CardPosition.TOP,
    glCardName: "phoebusApollo",
  },
  "Heidelbeere_LightGreen": {
    "speci": CardId.VACCINIUM_MYRTILLUS,
    "color": CardColor.BIRCH,
    "position": CardPosition.BOTTOM,
    glCardName: "blueberry",
  },
  "Alpen-Apollofalter_Blue": {
    "speci": CardId.PARNASSIUS_PHOEBUS,
    "color": CardColor.SILVER_FIR,
    "position": CardPosition.TOP,
    glCardName: "phoebusApollo",
  },
  "Bergmolch_Pink": {
    "speci": CardId.ICHTHYOSAURA_ALPESTRIS,
    "color": CardColor.PINUS,
    "position": CardPosition.BOTTOM,
    glCardName: "alpineNewt",
  },
  "Steinadler_Green": {
    "speci": CardId.AQUILA_CHRYSAETOS,
    "color": CardColor.BEECH,
    "position": CardPosition.TOP,
    glCardName: "goldenEagle",
  },
  "Herbsttrompete_Pink": {
    "speci": CardId.CRATERELLUS_CORNUCOPIODES,
    "color": CardColor.PINUS,
    "position": CardPosition.BOTTOM,
    glCardName: "blackTrumpet",
  },
  "Bartgeier_Blue": {
    "speci": CardId.GYPAETUS_BARBATUS,
    "color": CardColor.SILVER_FIR,
    "position": CardPosition.TOP,
    glCardName: "beardedVulture",
  },
  "Enzian_Lila": {
    "speci": CardId.GENTIANA,
    "color": CardColor.LARIX,
    "position": CardPosition.BOTTOM,
    glCardName: "gentian",
  },
  "Steinadler_Lila": {
    "speci": CardId.AQUILA_CHRYSAETOS,
    "color": CardColor.LARIX,
    "position": CardPosition.TOP,
    glCardName: "goldenEagle",
  },
  "Bergmolch_Grey": {
    "speci": CardId.ICHTHYOSAURA_ALPESTRIS,
    "color": CardColor.DOUGLAS_FIR,
    "position": CardPosition.BOTTOM,
    glCardName: "alpineNewt",
  },
  "Kolkrabe_Lila": {
    "speci": CardId.CORVUS_CORAX,
    "color": CardColor.LARIX,
    "position": CardPosition.TOP,
    glCardName: "commonRaven",
  },
  "Enzian_Green": {
    "speci": CardId.GENTIANA,
    "color": CardColor.BEECH,
    "position": CardPosition.BOTTOM,
    glCardName: "gentian",
  },
  "Kolkrabe_Grey": {
    "speci": CardId.CORVUS_CORAX,
    "color": CardColor.DOUGLAS_FIR,
    "position": CardPosition.TOP,
    glCardName: "commonRaven",
  },
  "Heidelbeere_Pink": {
    "speci": CardId.VACCINIUM_MYRTILLUS,
    "color": CardColor.PINUS,
    "position": CardPosition.BOTTOM,
    glCardName: "blueberry",
  },
  "Bartgeier_Lila": {
    "speci": CardId.GYPAETUS_BARBATUS,
    "color": CardColor.LARIX,
    "position": CardPosition.TOP,
    glCardName: "beardedVulture",
  },
  "Bergmolch_Blue": {
    "speci": CardId.ICHTHYOSAURA_ALPESTRIS,
    "color": CardColor.SILVER_FIR,
    "position": CardPosition.BOTTOM,
    glCardName: "alpineNewt",
  },
  "Bartgeier_Pink": {
    "speci": CardId.GYPAETUS_BARBATUS,
    "color": CardColor.PINUS,
    "position": CardPosition.TOP,
    glCardName: "beardedVulture",
  },
  "Edelweis_Lila": {
    "speci": CardId.LEONTOPODIUM_NIVALE,
    "color": CardColor.LARIX,
    "position": CardPosition.BOTTOM,
    glCardName: "edelweiss",
  },
  "Steinadler_Blue": {
    "speci": CardId.AQUILA_CHRYSAETOS,
    "color": CardColor.SILVER_FIR,
    "position": CardPosition.TOP,
    glCardName: "goldenEagle",
  },
  "Enzian_Pink": {
    "speci": CardId.GENTIANA,
    "color": CardColor.PINUS,
    "position": CardPosition.BOTTOM,
    glCardName: "gentian",
  },
  "Alpenfledermaus_Left_Lila": {
    "speci": CardId.HYPSUGO_SAVII,
    "color": CardColor.LARIX,
    "position": CardPosition.LEFT,
    glCardName: "savisPipistrelle",
  },
  "Schneehase_Right_Pink": {
    "speci": CardId.LEPUS_TIMIDUS,
    "color": CardColor.PINUS,
    "position": CardPosition.RIGHT,
    glCardName: "mountainHare",
  },
  "Holunder_Yellow": {
    "speci": CardId.SAMBUCUS,
    "color": CardColor.LINDEN,
    "position": CardPosition.BASE,
    glCardName: "elderberry",
  },
  "Holunder_Red": {
    "speci": CardId.SAMBUCUS,
    "color": CardColor.SYCAMORE,
    "position": CardPosition.BASE,
    glCardName: "elderberry",
  },
  "Holunder_LightGreen": {
    "speci": CardId.SAMBUCUS,
    "color": CardColor.BIRCH,
    "position": CardPosition.BASE,
    glCardName: "elderberry",
  },
  "Holunder_Brown": {
    "speci": CardId.SAMBUCUS,
    "color": CardColor.OAK,
    "position": CardPosition.BASE,
    glCardName: "elderberry",
  },
  "Haselnuss_Orange": {
    "speci": CardId.COMMON_HAZEL,
    "color": CardColor.HORSE_CHESTNUT,
    "position": CardPosition.BASE,
    glCardName: "commonHazel",
  },
  "Haselnuss_Brown": {
    "speci": CardId.COMMON_HAZEL,
    "color": CardColor.OAK,
    "position": CardPosition.BASE,
    glCardName: "commonHazel",
  },
  "Haselnuss_Green": {
    "speci": CardId.COMMON_HAZEL,
    "color": CardColor.BEECH,
    "position": CardPosition.BASE,
    glCardName: "commonHazel",
  },
  "Haselnuss_LightGreen": {
    "speci": CardId.COMMON_HAZEL,
    "color": CardColor.BIRCH,
    "position": CardPosition.BASE,
    glCardName: "commonHazel",
  },
  "Schlehdorn_Grey": {
    "speci": CardId.BLACKTHORN,
    "color": CardColor.DOUGLAS_FIR,
    "position": CardPosition.BASE,
    glCardName: "blackthorn",
  },
  "Schlehdorn_LightGreen": {
    "speci": CardId.BLACKTHORN,
    "color": CardColor.BIRCH,
    "position": CardPosition.BASE,
    glCardName: "blackthorn",
  },
  "Schlehdorn_Blue": {
    "speci": CardId.BLACKTHORN,
    "color": CardColor.SILVER_FIR,
    "position": CardPosition.BASE,
    glCardName: "blackthorn",
  },
  "Schlehdorn_Red": {
    "speci": CardId.BLACKTHORN,
    "color": CardColor.SYCAMORE,
    "position": CardPosition.BASE,
    glCardName: "blackthorn",
  },
  "Landkaertchen_Yellow": {
    "speci": CardId.MAP_BUTTERFLY,
    "color": CardColor.LINDEN,
    "position": CardPosition.TOP,
    glCardName: "mapButterfly",
  },
  "Fingerhut_Grey": {
    "speci": CardId.DIGITALIS,
    "color": CardColor.DOUGLAS_FIR,
    "position": CardPosition.BOTTOM,
    glCardName: "digitalis",
  },
  "Landkaertchen_Red": {
    "speci": CardId.MAP_BUTTERFLY,
    "color": CardColor.SYCAMORE,
    "position": CardPosition.TOP,
    glCardName: "mapButterfly",
  },
  "Brennnessel_LightGreen": {
    "speci": CardId.URTICA,
    "color": CardColor.BIRCH,
    "position": CardPosition.BOTTOM,
    glCardName: "stingingNettle",
  },
  "Landkaertchen_Brown": {
    "speci": CardId.MAP_BUTTERFLY,
    "color": CardColor.OAK,
    "position": CardPosition.TOP,
    glCardName: "mapButterfly",
  },
  "Gruenes-Heupferd_Blue": {
    "speci": CardId.GREAT_GREEN_BUSH_CRICKET,
    "color": CardColor.SILVER_FIR,
    "position": CardPosition.BOTTOM,
    glCardName: "greatGreenBushCricket",
  },
  "Landkaertchen_Blue": {
    "speci": CardId.MAP_BUTTERFLY,
    "color": CardColor.SILVER_FIR,
    "position": CardPosition.TOP,
    glCardName: "mapButterfly",
  },
  "Schermaus_Red": {
    "speci": CardId.EUROPEAN_WATER_VOLE,
    "color": CardColor.SYCAMORE,
    "position": CardPosition.BOTTOM,
    glCardName: "waterVole",
  },
  "Elster_Green": {
    "speci": CardId.EURASIAN_MAGPIE,
    "color": CardColor.BEECH,
    "position": CardPosition.TOP,
    glCardName: "eurasianMagpie",
  },
  "Fingerhut_LightGreen": {
    "speci": CardId.DIGITALIS,
    "color": CardColor.BIRCH,
    "position": CardPosition.BOTTOM,
    glCardName: "digitalis",
  },
  "Elster_Blue": {
    "speci": CardId.EURASIAN_MAGPIE,
    "color": CardColor.SILVER_FIR,
    "position": CardPosition.TOP,
    glCardName: "eurasianMagpie",
  },
  "Brennnessel_Orange": {
    "speci": CardId.URTICA,
    "color": CardColor.HORSE_CHESTNUT,
    "position": CardPosition.BOTTOM,
    glCardName: "stingingNettle",
  },
  "Elster_LightGreen": {
    "speci": CardId.EURASIAN_MAGPIE,
    "color": CardColor.BIRCH,
    "position": CardPosition.TOP,
    glCardName: "eurasianMagpie",
  },
  "Gruenes-Heupferd_Green": {
    "speci": CardId.GREAT_GREEN_BUSH_CRICKET,
    "color": CardColor.BEECH,
    "position": CardPosition.BOTTOM,
    glCardName: "greatGreenBushCricket",
  },
  "Nachtigall_Green": {
    "speci": CardId.COMMON_NIGHTINGALE,
    "color": CardColor.BEECH,
    "position": CardPosition.TOP,
    glCardName: "nightingale",
  },
  "Fingerhut_Red": {
    "speci": CardId.DIGITALIS,
    "color": CardColor.SYCAMORE,
    "position": CardPosition.BOTTOM,
    glCardName: "digitalis",
  },
  "Nachtigall_Brown": {
    "speci": CardId.COMMON_NIGHTINGALE,
    "color": CardColor.OAK,
    "position": CardPosition.TOP,
    glCardName: "nightingale",
  },
  "Brennnessel_Red": {
    "speci": CardId.URTICA,
    "color": CardColor.SYCAMORE,
    "position": CardPosition.BOTTOM,
    glCardName: "stingingNettle",
  },
  "Nachtigall_Orange": {
    "speci": CardId.COMMON_NIGHTINGALE,
    "color": CardColor.HORSE_CHESTNUT,
    "position": CardPosition.TOP,
    glCardName: "nightingale",
  },
  "Schermaus_Green": {
    "speci": CardId.EUROPEAN_WATER_VOLE,
    "color": CardColor.BEECH,
    "position": CardPosition.BOTTOM,
    glCardName: "waterVole",
  },
  "Schleiereule_LightGreen": {
    "speci": CardId.BARN_OWL,
    "color": CardColor.BIRCH,
    "position": CardPosition.TOP,
    glCardName: "barnOwl",
  },
  "Fingerhut_Brown": {
    "speci": CardId.DIGITALIS,
    "color": CardColor.OAK,
    "position": CardPosition.BOTTOM,
    glCardName: "digitalis",
  },
  "Schleiereule_Red": {
    "speci": CardId.BARN_OWL,
    "color": CardColor.SYCAMORE,
    "position": CardPosition.TOP,
    glCardName: "barnOwl",
  },
  "Gruenes-Heupferd_Brown": {
    "speci": CardId.GREAT_GREEN_BUSH_CRICKET,
    "color": CardColor.OAK,
    "position": CardPosition.BOTTOM,
    glCardName: "greatGreenBushCricket",
  },
  "Bache_Left_LightGreen": {
    "speci": CardId.WILD_BOAR_FEMALE,
    "color": CardColor.BIRCH,
    "position": CardPosition.LEFT,
    glCardName: "wildBoarFemale",
  },
  "Bienenschwarm_Right_Red": {
    "speci": CardId.BEEHIVE,
    "color": CardColor.SYCAMORE,
    "position": CardPosition.RIGHT,
    glCardName: "beeSwarm",
  },
  "Wisent_Left_Brown": {
    "speci": CardId.EUROPEAN_BISON,
    "color": CardColor.OAK,
    "position": CardPosition.LEFT,
    glCardName: "europeanBison",
  },
  "Bache_Right_Red": {
    "speci": CardId.WILD_BOAR_FEMALE,
    "color": CardColor.SYCAMORE,
    "position": CardPosition.RIGHT,
    glCardName: "wildBoarFemale",
  },
  "Bache_Left_Blue": {
    "speci": CardId.WILD_BOAR_FEMALE,
    "color": CardColor.SILVER_FIR,
    "position": CardPosition.LEFT,
    glCardName: "wildBoarFemale",
  },
  "Wildkatze_Right_Orange": {
    "speci": CardId.EUROPEAN_WILDCAT,
    "color": CardColor.HORSE_CHESTNUT,
    "position": CardPosition.RIGHT,
    glCardName: "europeanWildcat",
  },
  "Zwergfledermaus_Left_Yellow": {
    "speci": CardId.COMMON_PIPISTRELLE,
    "color": CardColor.LINDEN,
    "position": CardPosition.LEFT,
    glCardName: "commonPipistrelle",
  },
  "Frischling-Waldrand_Right_Blue": {
    "speci": CardId.SQUEAKER_EDGE,
    "color": CardColor.SILVER_FIR,
    "position": CardPosition.RIGHT,
    glCardName: "squeakerWE",
  },
  "Frischling-Waldrand_Left_Orange": {
    "speci": CardId.SQUEAKER_EDGE,
    "color": CardColor.HORSE_CHESTNUT,
    "position": CardPosition.LEFT,
    glCardName: "squeakerWE",
  },
  "Schnake_Right_Green": {
    "speci": CardId.MOSQUITO,
    "color": CardColor.BEECH,
    "position": CardPosition.RIGHT,
    glCardName: "craneFly",
  },
  "Waldiltis_Left_Blue": {
    "speci": CardId.EUROPEAN_POLECAT,
    "color": CardColor.SILVER_FIR,
    "position": CardPosition.LEFT,
    glCardName: "europeanPolecat",
  },
  "Frischling-Waldrand_Right_Grey": {
    "speci": CardId.SQUEAKER_EDGE,
    "color": CardColor.DOUGLAS_FIR,
    "position": CardPosition.RIGHT,
    glCardName: "squeakerWE",
  },
  "Bienenschwarm_Left_Green": {
    "speci": CardId.BEEHIVE,
    "color": CardColor.BEECH,
    "position": CardPosition.LEFT,
    glCardName: "beeSwarm",
  },
  "Zwergfledermaus_Right_Red": {
    "speci": CardId.COMMON_PIPISTRELLE,
    "color": CardColor.SYCAMORE,
    "position": CardPosition.RIGHT,
    glCardName: "commonPipistrelle",
  },
  "Wildkatze_Left_Brown": {
    "speci": CardId.EUROPEAN_WILDCAT,
    "color": CardColor.OAK,
    "position": CardPosition.LEFT,
    glCardName: "europeanWildcat",
  },
  "Bienenschwarm_Right_LightGreen": {
    "speci": CardId.BEEHIVE,
    "color": CardColor.BIRCH,
    "position": CardPosition.RIGHT,
    glCardName: "beeSwarm",
  },
  "Zwergfledermaus_Left_LightGreen": {
    "speci": CardId.COMMON_PIPISTRELLE,
    "color": CardColor.BIRCH,
    "position": CardPosition.LEFT,
    glCardName: "commonPipistrelle",
  },
  "Wisent_Right_Green": {
    "speci": CardId.EUROPEAN_BISON,
    "color": CardColor.BEECH,
    "position": CardPosition.RIGHT,
    glCardName: "europeanBison",
  },
  "Wisent_Left_Green": {
    "speci": CardId.EUROPEAN_BISON,
    "color": CardColor.BEECH,
    "position": CardPosition.LEFT,
    glCardName: "europeanBison",
  },
  "Waldiltis_Right_Red": {
    "speci": CardId.EUROPEAN_POLECAT,
    "color": CardColor.SYCAMORE,
    "position": CardPosition.RIGHT,
    glCardName: "europeanPolecat",
  },
  "Schnake_Left_LightGreen": {
    "speci": CardId.MOSQUITO,
    "color": CardColor.BIRCH,
    "position": CardPosition.LEFT,
    glCardName: "craneFly",
  },
  "Waldiltis_Right_Brown": {
    "speci": CardId.EUROPEAN_POLECAT,
    "color": CardColor.OAK,
    "position": CardPosition.RIGHT,
    glCardName: "europeanPolecat",
  },
  "Wildkatze_Left_Red": {
    "speci": CardId.EUROPEAN_WILDCAT,
    "color": CardColor.SYCAMORE,
    "position": CardPosition.LEFT,
    glCardName: "europeanWildcat",
  },
  "Schnake_Right_Brown": {
    "speci": CardId.MOSQUITO,
    "color": CardColor.OAK,
    "position": CardPosition.RIGHT,
    glCardName: "craneFly",
  }
}
